TRUNCATE asc_service.repair_request CASCADE;
ALTER SEQUENCE asc_service.repair_request_id_seq RESTART WITH 1;
TRUNCATE asc_service.device CASCADE;
TRUNCATE asc_service.service_center CASCADE;
TRUNCATE asc_service.employee CASCADE;
TRUNCATE asc_service.completed_work CASCADE;
ALTER SEQUENCE asc_service.completed_work_id_seq RESTART WITH 1;
TRUNCATE asc_service.completed_work_work_order CASCADE;
ALTER SEQUENCE asc_service.completed_work_work_order_completed_work_id_seq RESTART WITH 1;
ALTER SEQUENCE asc_service.completed_work_work_order_work_order_id_seq RESTART WITH 1;
TRUNCATE asc_service.outbox_event CASCADE;
ALTER SEQUENCE asc_service.outbox_event_id_seq RESTART WITH 1;
TRUNCATE asc_service.payment_result CASCADE;
TRUNCATE asc_service.payment_transactions CASCADE;
ALTER SEQUENCE asc_service.payment_transactions_id_seq RESTART WITH 1;
TRUNCATE asc_service.spare_part CASCADE;
TRUNCATE asc_service.spare_part_work_order CASCADE;
ALTER SEQUENCE asc_service.spare_part_work_order_spare_part_id_seq RESTART WITH 1;
ALTER SEQUENCE asc_service.spare_part_work_order_work_order_id_seq RESTART WITH 1;
TRUNCATE asc_service.work_order CASCADE;
ALTER SEQUENCE asc_service.work_order_id_seq RESTART WITH 1;
